account/urls.py
from django.urls import path
from .views import   OtpLoginView , CheckOtp , AddAddress,LoginUser
from . import views

app_name = 'account'
urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', OtpLoginView.as_view(), name='register'),
    path('check/', CheckOtp.as_view(), name='check'),
    path('address/', AddAddress.as_view(), name='add_address'),
    path('address/', AddAddress.as_view(), name='add_address'),
]

cart/urls.py
from django.urls import path
from .views import CartView,CartAdd,CartDelete,OrderDetail,OrderCreation,ApplyDiscount,SendRequest,verify

app_name = 'cart'
urlpatterns = [
    path('cart/',CartView.as_view(), name='cart'),
    path('add/<int:pk>', CartAdd.as_view(), name='cart_add'),
    path('delete/<str:id>', CartDelete.as_view(), name='cart_delete'),
    path('order/<int:pk>', OrderDetail.as_view(), name='order_detail'),
    path('order/create', OrderCreation.as_view(), name='order_create'),
    path('discount/<int:pk>', ApplyDiscount.as_view(), name='discount'),
    path('send/<int:pk>', SendRequest.as_view(), name='send_request_pay'),
    path('verify/', verify, name='verify'),
]

home/urls.py
from django.urls import path
from .views import HomeView


app_name = 'home'
urlpatterns =[
    path('', HomeView.as_view(), name='landing'),

]

product/urls.py
from django.urls import path
from .views import NavBar, ProductList, searchview, product_detail

app_name = 'product'

urlpatterns = [
    path('detail/<int:pk>', product_detail , name='detail'),
    path('all/', ProductList.as_view(), name='product_all'),
    path('category/', NavBar.as_view(), name='navbar'),
    path('search/', searchview, name='search'),

]

shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from account.models import User
from product.models import Product


class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, null=True, blank=True)
    phone = models.CharField(max_length=12, blank=True, null=True)
    address = models.TextField(blank=True,null=True)
    email = models.EmailField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    total_price = models.IntegerField(default=0)
    is_paid = models.BooleanField(default=False)

    def __str__(self):
        return self.user.phone


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE,related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='items')
    size = models.CharField(max_length=15, blank=True, null=True)
    color = models.CharField(max_length=30, blank=True, null=True)
    quantity = models.IntegerField(blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)


class DiscountCode(models.Model):
    name = models.CharField(max_length=10,unique=True)
    discount = models.IntegerField(default=0, blank=True, null=True)
    quantity = models.SmallIntegerField(default=1)

    def __str__(self):
        return self.name

cart/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.views.generic import View
from account.models import Address
from product.models import Product
from .cart_module import Cart
from .models import Order, OrderItem, DiscountCode
from django.conf import settings
import requests
import json


# Display cart
class CartView(View):
    def get(self, request):
        cart = Cart(request)
        return render(request, 'cart/cart.html', {'cart': cart})


# Add product to cart
class CartAdd(View):
    def post(self, request, pk):
        product = get_object_or_404(Product, id=pk)
        size, color, quantity = request.POST.get('size', 'empty'), request.POST.get('color', 'empty'), request.POST.get(
            'quantity')
        cart = Cart(request)
        cart.add(product, color, size, quantity)

        return redirect('cart:cart')

# Remove the selected product from the shopping cart
class CartDelete(View):
    def get(self, request, id):
        cart = Cart(request)
        cart.delete(id)
        return redirect('cart:cart')

# order detail
class OrderDetail(LoginRequiredMixin, View):
    def get(self, request, pk):
        order = get_object_or_404(Order, id=pk)
        return render(request, 'cart/cart_detail.html', {'order': order})

# order detail
class OrderCreation(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)

        order = Order.objects.create(user=request.user, total_price=cart.total())
        for item in cart:
            OrderItem.objects.create(order=order, product=item['product'], price=item['price'],
                                     size=item['size'], color=item['color'], quantity=item['quantity'], )

            cart.remove_cart()
            return redirect('cart:order_detail', order.id)


# Creating and applying a discount code
class ApplyDiscount(LoginRequiredMixin, View):
    def post(self, request, pk):
        order = get_object_or_404(Order, id=pk)
        code = request.POST.get('discount_code')
        discount_code = get_object_or_404(DiscountCode, name=code)
        if discount_code.quantity == 0:
            return redirect('cart:order_detail', order.id)
        order.total_price -= order.total_price * discount_code.discount / 100
        order.save()
        discount_code.quantity -= 1
        discount_code.save()
        return redirect('cart:order_detail', order.id)

# Payment gateway page
if settings.SANDBOX:
    sandbox = 'sandbox'
else:
    sandbox = 'www'

ZP_API_REQUEST = f"https://{sandbox}.zarinpal.com/pg/rest/WebGate/PaymentRequest.json"
ZP_API_VERIFY = f"https://{sandbox}.zarinpal.com/pg/rest/WebGate/PaymentVerification.json"
ZP_API_STARTPAY = f"https://{sandbox}.zarinpal.com/pg/StartPay/"

amount = 1000  # Rial / Required
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"  # Required
phone = 'YOUR_PHONE_NUMBER'  # Optional
# Important: need to edit for realy server.
CallbackURL = 'http://127.0.0.1:8000/cart/verify/'


class SendRequest(View):
    def post(self, request, pk):
        order = get_object_or_404(Order, id=pk, user=request.user)
        address = get_object_or_404(Address, id=request.POST.get('address'))
        order.address = f'{address.address}-{address.phone}'
        order.save()
        request.session['order_id'] = str(order.id)
        data = {
            "MerchantID": settings.MERCHANT,
            "Amount": order.total_price,
            "Description": description,
            "Phone": request.user.phone,
            "CallbackURL": CallbackURL,
        }
        data = json.dumps(data)
        # set content length by data
        headers = {'content-type': 'application/json', 'content-length': str(len(data))}
        try:
            response = requests.post(ZP_API_REQUEST, data=data, headers=headers, timeout=10)

            if response.status_code == 200:
                response = response.json()
                if response['Status'] == 100:
                    return {'status': True, 'url': ZP_API_STARTPAY + str(response['Authority']),
                            'authority': response['Authority']}
                else:
                    return {'status': False, 'code': str(response['Status'])}
            return response

        except requests.exceptions.Timeout:
            return {'status': False, 'code': 'timeout'}
        except requests.exceptions.ConnectionError:
            return {'status': False, 'code': 'connection error'}


def verify(authority):
    order_id = requests.session['order_id']
    order = Order.objects.get(id=int(order_id))
    data = {
        "MerchantID": settings.MERCHANT,
        "Amount": order.total_price,
        "Authority": authority,
    }

    data = json.dumps(data)
    # set content length by data
    headers = {'content-type': 'application/json', 'content-length': str(len(data))}
    response = requests.post(ZP_API_VERIFY, data=data, headers=headers)

    if response.status_code == 200:
        response = response.json()

        if response['Status'] == 100:
            order.is_paid = True
            order.save()
            return {'status': True, 'RefID': response['RefID']}
        else:
            return {'status': False, 'code': str(response['Status'])}
    return response

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'home:landing' %}">Home</a>
                    <a class="breadcrumb-item text-dark" href="{% url 'product:product_all' %}">Product</a>
                    <span class="breadcrumb-item active">Shopping Cart</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Products</th>
                            <th>title</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Color</th>
                            <th>Size</th>
                            <th>Total</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for item in cart %}
                         <tr>
                            <td class="align-middle"><img src="{{ item.product.img1.url }}" alt="" style="width: 50px;"> </td>
                            <td class="align-middle">{{ item.product.title }}</td>
                            <td class="align-middle">${{ item.price }}</td>
                            <td class="align-middle"> {{ item.quantity }}</td>
                            <td class="align-middle">{{ item.color }}</td>
                            <td class="align-middle">{{ item.size}}</td>
                            <td class="align-middle">${{ item.total }}</td>
                            <td class="align-middle"><a href="{% url 'cart:cart_delete' item.unique_id %}" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a></td>
                        </tr>
                        {% endfor %}


                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" action="">
                    <div class="input-group">
                        <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">

                    </div>

                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>${{ cart.total }}</h5>
                        </div>
                        <a href="{% url 'cart:order_create'  %}" class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->

{% endblock %}

cart/templates/cart/cart_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'home:landing' %}">Home</a>
                    <a class="breadcrumb-item text-dark" href="{% url 'product:product_all' %}">Shop</a>
                    <span class="breadcrumb-item active">Shopping Cart</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                    <tr>
                        <th>Products</th>
                        <th>title</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Color</th>
                        <th>Size</th>


                    </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for items in order.items.all %}
                        <tr>
                            <td class="align-middle"><img src="{{ items.product.img1.url }}" alt="" style="width: 50px;">
                            </td>
                            <td class="align-middle"> {{ items.product.title }}</td>
                            <td class="align-middle">${{ items.price }}</td>
                            <td class="align-middle"> {{ items.quantity }}</td>
                            <td class="align-middle">{{ items.color }}</td>
                            <td class="align-middle">{{ items.size }}</td>

                        </tr>
                         {% endfor %}


                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" action="{% url 'cart:discount' order.id %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" class="form-control border-0 p-4" placeholder="Discount code" name="discount_code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span>
                </h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">
                    </div>

                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>${{ order.total_price }}</h5>
                        </div>
{#                        {% if request.user.addresses.all %}#}
{#                            <a href="{% url 'cart:order_create' %}"#}
{#                               class="btn btn-block btn-success font-weight-bold my-3 py-3">Pay</a>#}
{#                        {% endif %}#}

                        {% if request.user.addresses.all %}
                           <form action="{% url 'cart:send_request_pay' order.id %}" method="post">
                           {% csrf_token %}
                            <select name="address" class="form-control" aria-label="Default select example">
                            {% for address in request.user.addresses.all %}
                                <option value="{{ address.address }}">{{ address.address }}</option>
                            {% endfor %}
                            </select>

                               <a href="{% url 'account:add_address' %}?next={% url 'cart:order_detail' order.id %}"
                               class="btn btn-block btn-primary font-weight-bold my-3 py-3">add another address</a>

                           <button type="submit"
                               class="btn btn-block btn-success font-weight-bold my-3 py-3">Pay</button>


                           </form>
                        {% else %}
                           <a href="{% url 'account:add_address' %}?next={% url 'cart:order_detail' order.id %}"
                               class="btn btn-block btn-primary font-weight-bold my-3 py-3">add address</a>

                        {% endif %}

                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->

{% endblock %}