account/urls.py
from django.urls import path
from .views import   OtpLoginView , CheckOtp , AddAddress,LoginUser
from . import views

app_name = 'account'
urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', OtpLoginView.as_view(), name='register'),
    path('check/', CheckOtp.as_view(), name='check'),
    path('address/', AddAddress.as_view(), name='add_address'),
    path('address/', AddAddress.as_view(), name='add_address'),
]

cart/urls.py
from django.urls import path
from .views import CartView,CartAdd,CartDelete,OrderDetail,OrderCreation,ApplyDiscount,SendRequest,verify

app_name = 'cart'
urlpatterns = [
    path('cart/',CartView.as_view(), name='cart'),
    path('add/<int:pk>', CartAdd.as_view(), name='cart_add'),
    path('delete/<str:id>', CartDelete.as_view(), name='cart_delete'),
    path('order/<int:pk>', OrderDetail.as_view(), name='order_detail'),
    path('order/create', OrderCreation.as_view(), name='order_create'),
    path('discount/<int:pk>', ApplyDiscount.as_view(), name='discount'),
    path('send/<int:pk>', SendRequest.as_view(), name='send_request_pay'),
    path('verify/', verify, name='verify'),
]

contact/urls.py
from django.urls import path
from .views import contactview

app_name = 'contact'
urlpatterns = [
    path('contact/', contactview, name='contact')
]

home/urls.py
from django.urls import path
from .views import HomeView


app_name = 'home'
urlpatterns =[
    path('', HomeView.as_view(), name='landing'),

]

product/urls.py
from django.urls import path
from .views import NavBar, ProductList, searchview, product_detail

app_name = 'product'

urlpatterns = [
    path('detail/<int:pk>', product_detail , name='detail'),
    path('all/', ProductList.as_view(), name='product_all'),
    path('category/', NavBar.as_view(), name='navbar'),
    path('search/', searchview, name='search'),

]

shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/include/footer.html
{% load static %}
{% load social_share %}

<!-- Footer Start -->
<div class="container-fluid bg-dark text-secondary mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <h5 class="text-secondary text-uppercase mb-4">Get In Touch</h5>
            <p class="mb-4">You can either in person or by phone Be in touch with us
                Be in touch with us</p>
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">Quick Shop</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-secondary mb-2" href="{% url 'home:landing' %}"><i
                                class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-secondary mb-2" href="{% url 'product:product_all' %}"><i
                                class="fa fa-angle-right mr-2"></i>Product</a>
                        <a class="text-secondary mb-2" href="{% url 'cart:cart' %}"><i
                                class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                        <a class="text-secondary" href="{% url 'contact:contact' %}"><i
                                class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">My Account</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-secondary mb-2" href="{% url 'home:landing' %}"><i
                                class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-secondary mb-2" href="{% url 'account:login' %}"><i
                                class="fa fa-angle-right mr-2"></i>Login/Register</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>FAQS</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>About</a>
                        <a class="text-secondary" href="{% url 'contact:contact' %}"><i
                                class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-3 mb-8">
                    <h6 class="text-secondary text-uppercase mb-4">Follow Us</h6>
                    <div class="d-flex">
                        <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-twitter"> </i></a>
                        <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                        <a class="btn btn-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-secondary">
                &copy; <a class="text-primary" href="#">Domain</a>. All Rights Reserved. Designed
                by
                <a class="text-primary" href="https://htmlcodex.com">HTML Codex</a>
            </p>
        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">
            <img class="img-fluid" src="{% static 'img/payments.png' %}" alt="">
        </div>
    </div>
</div>
<!-- Footer End -->

templates/include/footer_refrences.html
{% load static %}

   <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'mail/contact.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/include/head.html
{% load static %}
{% load render_partial %}



    <meta charset="utf-8">
    <title>MultiShop - Online Shop Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

templates/include/navbar.html
<div class="container-fluid bg-dark mb-30">
    <div class="row px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn d-flex align-items-center justify-content-between bg-primary w-100" data-toggle="collapse"
               href="#navbar-vertical" style="height: 65px; padding: 0 30px;">
                <h6 class="text-dark m-0"><i class="fa fa-bars mr-2"></i>Categories</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light"
                 id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">
                <div class="navbar-nav w-100">
                    {% for category in categories %}

                        {% if not category.parent %}
                            {% if category.category.all %}

                                <div class="nav-item dropdown dropright">
                                    <a href="#" class="nav-link dropdown-toggle"
                                       data-toggle="dropdown">{{ category.title }}<i
                                            class="fa fa-angle-right float-right mt-1"></i></a>
                                    <div class="dropdown-menu position-absolute rounded-0 border-0 m-0">
                                        {% for category in category.category.all %}
                                            <a href="" class="nav-item nav-link">{{ category.title }}</a>
                                        {% endfor %}

                                    </div>
                                </div>
                            {% else %}
                                <a href="" class="nav-item nav-link">{{ category.title }}</a>

                            {% endif %}
                        {% endif %}
                    {% endfor %}
            </nav>
        </div>

        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <span class="h1 text-uppercase text-dark bg-light px-2">Multi</span>
                    <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">Shop</span>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto ">
                        <a href="{% url 'home:landing' %}"
                           class="nav-item nav-link {% if request.resolver_match.url_name == 'landing' %}active{% endif %} ">Home</a>
                        <a href="{% url 'product:product_all' %}"
                           class="nav-item nav-link {% if request.resolver_match.url_name == 'product_all' %}active{% endif %}">Shop</a>
                        <div class="nav-item dropdown">
                            <a href="{% url 'cart:cart' %}"
                               class=" nav-item nav-link {% if request.resolver_match.url_name == 'cart' %}active{% endif %}">Shopping
                                Cart</a>
                        </div>
                        <a href="{% url 'contact:contact' %}"
                           class="nav-item nav-link {% if request.resolver_match.url_name == 'contact' %}active{% endif %}">Contact</a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>

templates/include/topbar.html
<div class="container-fluid">
        <div class="row bg-secondary py-1 px-xl-5">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="d-inline-flex align-items-center h-100">

                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">My Account</button>
                        <div class="dropdown-menu dropdown-menu-right">

                            <a class="dropdown-item" type="submit" href="{% url 'account:register' %}"> Login/Register </a>
                            <a class="dropdown-item" type="submit" href="{% url 'account:logout' %}">Logout</a>
                        </div>
                    </div>


                </div>
                <div class="d-inline-flex align-items-center d-block d-lg-none">
                    <a href="" class="btn px-0 ml-2">
                        <i class="fas fa-heart text-dark"></i>
                        <span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">0</span>
                    </a>
                    <a href="" class="btn px-0 ml-2">
                        <i class="fas fa-shopping-cart text-dark"></i>
                        <span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">0</span>
                    </a>
                </div>
            </div>
        </div>
        <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
            <div class="col-lg-4">
                <a href="{% url 'home:landing' %}" class="text-decoration-none">
                    <span class="h1 text-uppercase text-primary bg-dark px-2">Phone</span>
                    <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">Shop</span>
                </a>
            </div>
            <div class="col-lg-4 col-6 text-left">
                <form action="{% url 'product:search' %}"  method="get">
                    <div class="input-group">
                        <input type="search" class="form-control" name="search" placeholder="Search for products">
                        <div class="input-group-append">
                            <button class="input-group-text bg-transparent text-primary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-4 col-6 text-right">
                <p class="m-0">Customer Service</p>
                <h5 class="m-0">+012 345 6789</h5>
            </div>
        </div>
    </div>