cart/urls.py
from django.urls import path
from .views import CartView,CartAdd,CartDelete,OrderDetail,OrderCreation,ApplyDiscount,SendRequest,verify

app_name = 'cart'
urlpatterns = [
    path('cart/',CartView.as_view(), name='cart'),
    path('add/<int:pk>', CartAdd.as_view(), name='cart_add'),
    path('delete/<str:id>', CartDelete.as_view(), name='cart_delete'),
    path('order/<int:pk>', OrderDetail.as_view(), name='order_detail'),
    path('order/create', OrderCreation.as_view(), name='order_create'),
    path('discount/<int:pk>', ApplyDiscount.as_view(), name='discount'),
    path('send/<int:pk>', SendRequest.as_view(), name='send_request_pay'),
    path('verify/', verify, name='verify'),
]

home/urls.py
from django.urls import path
from .views import HomeView


app_name = 'home'
urlpatterns =[
    path('', HomeView.as_view(), name='landing'),

]

product/urls.py
from django.urls import path
from .views import NavBar, ProductList, searchview, product_detail

app_name = 'product'

urlpatterns = [
    path('detail/<int:pk>', product_detail , name='detail'),
    path('all/', ProductList.as_view(), name='product_all'),
    path('category/', NavBar.as_view(), name='navbar'),
    path('search/', searchview, name='search'),

]

shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from account.models import User


# Category model for products
class Category(models.Model):
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='category')
    title = models.CharField(max_length=100)
    img = models.ImageField(blank=True, null=True)
    slug = models.SlugField()

    def __str__(self):
        return self.title


# size model for product
class Size(models.Model):
    title = models.CharField(max_length=50,null=True,blank=True)

    def __str__(self):
        return self.title


# color model for product
class Color(models.Model):
    title = models.CharField(max_length=50,null=True,blank=True)

    def __str__(self):
        return self.title


# product model
class Product(models.Model):
    title = models.CharField(max_length=200)
    preview_txt = models.CharField(max_length=300, null=True, blank=True)
    img1 = models.ImageField()
    img2 = models.ImageField(null=True,blank=True)
    img3 = models.ImageField(null=True,blank=True)
    img4 = models.ImageField(null=True,blank=True)
    price = models.IntegerField(null=True, blank=True)
    discount = models.SmallIntegerField()
    size = models.ManyToManyField(Size, related_name='product')
    color = models.ManyToManyField(Color, related_name='product')
    category = models.ManyToManyField(Category)
    description = models.TextField(max_length=500)
    information = models.TextField(blank=True, null=True)
    create = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


# Product reviews
class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user', )
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product')
    text = models.TextField(null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

# banner of index
class Banner(models.Model):
    img1 = models.ImageField(null=True,blank=True)
    img2 = models.ImageField(null=True,blank=True)
    title = models.CharField(max_length=100, null=True, blank=True)
    text = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.title

product/forms.py
from django import forms
from .models import ProductReview

product/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.views.generic import DetailView, TemplateView, ListView
from product.models import Product, Category, ProductReview

# Detail product page
def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        text = request.POST.get('text')
        name = request.POST.get('name')
        email = request.POST.get('email')
        ProductReview.objects.create(text=text, name=name, email=email, user=request.user, product=product)

    return render(request, 'product/detail.html', {'product': product})

# navbar-category
class NavBar(TemplateView):
    template_name = 'include/navbar.html'

    def get_context_data(self, **kwargs):
        context = super(NavBar, self).get_context_data()
        context['categories'] = Category.objects.all()
        return context

# product list
class ProductList(ListView):
    template_name = 'product/product_list.html'
    queryset = Product.objects.all()
    paginate_by = 3

    def get_context_data(self, **kwargs):
        request = self.request
        colors = request.GET.getlist('color')
        sizes = request.GET.getlist('size')
        min_price = request.GET.get('min_price')
        max_price = request.GET.get('max_price')
        queryset = Product.objects.all()
        print(colors, sizes,min_price, max_price)

        if colors:
            queryset = queryset.filter(color__title__in=colors).distinct()
        if sizes:
            queryset = queryset.filter(size__title__in=sizes).distinct()

        if min_price and max_price:
            queryset = queryset.filter(price__lte=max_price,price__gte=min_price)

        context = super(ProductList, self).get_context_data()
        context['object_list'] = queryset
        return context

# search bar
def searchview(request):
    search = request.GET.get('search')
    product_list = Product.objects.filter(title__icontains=search)
    return render(request, 'product/product_list.html', {'product_list': product_list})

product/templates/product/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}




    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'home:landing' %}">Home</a>
                    <span class="breadcrumb-item active">Product Detail</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Shop Detail Start -->
    <div class="container-fluid pb-5">
        <div class="row px-xl-5">
            <div class="col-lg-5 mb-30">
                <div id="product-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner bg-light">
                        <div class="carousel-item active">
                            <img class="w-100 h-100" src="{{ product.img1.url }}" alt="Image">
                        </div>

                        <div class="carousel-item">
                            <img class="w-100 h-100" src="{{ product.img2.url }}" alt="Image">
                        </div>
                        <div class="carousel-item">
                            <img class="w-100 h-100" src="{{ product.img3.url }}" alt="Image">
                        </div>
                        <div class="carousel-item">
                            <img class="w-100 h-100" src="{{ product.img4.url }}" alt="Image">
                        </div>
                    </div>

                    <a class="carousel-control-prev" href="#product-carousel" data-slide="prev">
                        <i class="fa fa-2x fa-angle-left text-dark"></i>
                    </a>
                    <a class="carousel-control-next" href="#product-carousel" data-slide="next">
                        <i class="fa fa-2x fa-angle-right text-dark"></i>
                    </a>

                </div>
            </div>

            <div class="col-lg-7 h-auto mb-30">
                <div class="h-100 bg-light p-30">
                    <h3> {{ product.title }}</h3>
                    <h3 class="font-weight-semi-bold mb-4">${{ product.price }}</h3>
                    <p class="mb-4">{{ product.description }}</p>


                    <div class="d-flex mb-3">
                        <strong class="text-dark mr-3">Sizes:</strong>
                        <form method="post" action="{% url 'cart:cart_add' product.id %}">
                            {% csrf_token %}

                            {% for size in product.size.all %}

                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" class="custom-control-input" id="{{ size.title }}"
                                           value="{{ size.title }}" name="size">
                                    <label class="custom-control-label" for="{{ size.title }}">{{ size.title }}</label>
                                </div>
                            {% endfor %}
                    </div>

                    <div class="d-flex mb-4">
                        <strong class="text-dark mr-3">Colors:</strong>

                        {% for color in product.color.all %}
                            <div class="custom-control custom-radio custom-control-inline">
                                <input type="radio" class="custom-control-input" value="{{ color.title }}"
                                       id="{{ color.title }}" name="color">
                                <label class="custom-control-label" for="{{ color.title }}">{{ color.title }}</label>
                            </div>
                        {% endfor %}

                    </div>
                    <div class="d-flex align-items-center mb-4 pt-2">
                        <div class="input-group quantity mr-3" style="width: 130px;">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary btn-minus">
                                    <i class="fa fa-minus"></i>
                                </button>
                            </div>
                            <input type="text" name="quantity" class="form-control bg-secondary border-0 text-center"
                                   value="1">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary btn-plus">
                                    <i class="fa fa-plus"></i>
                                </button>
                            </div>
                        </div>
                        <button class="btn btn-primary px-3"><i class="fa fa-shopping-cart mr-1"></i> Add To
                            Cart
                        </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row px-xl-5">
            <div class="col">
                <div class="bg-light p-30">
                    <div class="nav nav-tabs mb-4">
                        <a class="nav-item nav-link text-dark active" data-toggle="tab"
                           href="#tab-pane-1">Description</a>
                        <a class="nav-item nav-link text-dark" data-toggle="tab" href="#tab-pane-2">Information</a>
                        <a class="nav-item nav-link text-dark" data-toggle="tab" href="#tab-pane-3">Reviews</a>
                    </div>
                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="tab-pane-1">
                            <h4 class="mb-3">Product Description</h4>
                            <p>{{ product.description }}  </p>

                        </div>
                        <div class="tab-pane fade" id="tab-pane-2">
                            <h4 class="mb-3">Additional Information</h4>
                            <p></p>

                            <div class="row">

                                <div class="col-md-6">

                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item px-0">
                                            {{ product.information }}
                                        </li>
                                    </ul>

                                </div>
                                <div class="col-md-6">
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item px-0"></li>

                                    </ul>
                                </div>

                            </div>

                        </div>
                        <div class="tab-pane fade" id="tab-pane-3">
                            <div class="row">
                                <div class="col-md-6">
                                    <h4 class="mb-4"> review for "{{ product.title }}"</h4>
                                    {% for item in product.product.all %}

                                        <div class="media mb-4">
                                            <div class="media-body">
                                                <h6>{{ item.name }}<small> - <i>{{ item.create }}</i></small></h6>
                                                <p>{{ item.text }}. </p>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                                <div class="col-md-6">
                                    <h4 class="mb-4">Leave a review</h4>
                                    <small>Your email address will not be published. Required fields are marked
                                        *</small>
                                    <form method="post">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label for="text">Your Review *</label>
                                            <textarea id="text" cols="30" rows="5" class="form-control"
                                                      name="text"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label for="name">Your Name *</label>
                                            <input type="text" class="form-control" id="name" name="name">
                                        </div>
                                        <div class="form-group">
                                            <label for="email">Your Email *</label>
                                            <input type="email" class="form-control" id="email" name="email">
                                        </div>
                                        <div class="form-group mb-0">
                                            <input type="submit" value="Leave Your Review" class="btn btn-primary px-3">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Shop Detail End -->


    <!-- Products Start -->
    <div class="container-fluid py-5">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">You May Also Like</span>
        </h2>
        <div class="row px-xl-5">
            <div class="col">
                <div class="owl-carousel related-carousel">
                    {% for recent in recent_product %}



                        <div class="product-item bg-light">
                            <div class="product-img position-relative overflow-hidden">
                                <img class="img-fluid w-100" src="{{ recent.img1.url }}" alt="">
                                <div class="product-action">
                                    <a class="btn btn-outline-dark btn-square" href=""><i
                                            class="fa fa-shopping-cart"></i></a>
                                    <a class="btn btn-outline-dark btn-square" href=""><i class="far fa-heart"></i></a>
                                    <a class="btn btn-outline-dark btn-square" href=""><i
                                            class="fa fa-sync-alt"></i></a>
                                    <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-search"></i></a>
                                </div>
                            </div>
                            <div class="text-center py-4">
                                <a class="h6 text-decoration-none text-truncate" href="">{{ recent.title }}</a>
                                <div class="d-flex align-items-center justify-content-center mt-2">
                                    <h5>${{ recent.price }}</h5>

                                </div>

                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- Products End -->


{% endblock %}

product/templates/product/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}






    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'home:landing' %}">Home</a>

                    <span class="breadcrumb-item active">Product List</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Shop Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <!-- Shop Sidebar Start -->
            <div class="col-lg-3 col-md-4">
                <!-- Price Start -->
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by price</span>
                </h5>
                <form>

                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <label for="price-all">Min</label>
                        <input type="number" name="min_price" id="price-all">

                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <label for="price-all">Max</label>
                        <input type="number" name="max_price" id="price-all">
                    </div>
                    <!-- Price End -->

                    <!-- Color Start -->
                    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by color</span>
                    </h5>
                    <div class="bg-light p-4 mb-30">


                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <input type="checkbox" name="color" value="Black" class="custom-control-input" id="color-1">
                            <label class="custom-control-label" for="color-1">Black</label>

                        </div>
                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <input type="checkbox" name="color" value="White" class="custom-control-input" id="color-2">
                            <label class="custom-control-label" for="color-2">White</label>

                        </div>
                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <input type="checkbox" name="color" value="Red" class="custom-control-input" id="color-3">
                            <label class="custom-control-label" for="color-3">Red</label>

                        </div>
                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <input type="checkbox" name="color" value="Blue" class="custom-control-input" id="color-4">
                            <label class="custom-control-label" for="color-4">Blue</label>

                        </div>
                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between">
                            <input type="checkbox" name="color" value="Green" class="custom-control-input" id="color-5">
                            <label class="custom-control-label" for="color-5">Green</label>

                        </div>

                    </div>
                    <!-- Color End -->

                    <!-- Size Start -->
                    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by size</span>
                    </h5>
                    <div class="bg-light p-4 mb-30">


                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <input type="checkbox" name="size" value="small" class="custom-control-input" id="size-1">
                            <label class="custom-control-label" for="size-1">small</label>

                        </div>

                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between">
                            <input type="checkbox" name="size" value="big" class="custom-control-input" id="size-5">
                            <label class="custom-control-label" for="size-5">big</label>

                        </div>
                        <input type="submit">
                </form>
            </div>
            <!-- Size End -->
        </div>
        <!-- Shop Sidebar End -->


        <!-- Shop Product Start -->
        <div class="col-lg-9 col-md-8">
            <div class="row pb-3">
                <div class="col-12 pb-1">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <div>
                            <button class="btn btn-sm btn-light"><i class="fa fa-th-large"></i></button>
                            <button class="btn btn-sm btn-light ml-2"><i class="fa fa-bars"></i></button>
                        </div>
                        <div class="ml-2">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-light dropdown-toggle"
                                        data-toggle="dropdown">Sorting
                                </button>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="#">Latest</a>
                                    <a class="dropdown-item" href="#">Popularity</a>
                                    <a class="dropdown-item" href="#">Best Rating</a>
                                </div>
                            </div>
                            <div class="btn-group ml-2">
                                <button type="button" class="btn btn-sm btn-light dropdown-toggle"
                                        data-toggle="dropdown">Showing
                                </button>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="#">10</a>
                                    <a class="dropdown-item" href="#">20</a>
                                    <a class="dropdown-item" href="#">30</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% for product in product_list %}
                <div class="col-lg-4 col-md-6 col-sm-6 pb-1">
                    <div class="product-item bg-light mb-4">
                        <div class="product-img position-relative overflow-hidden">
                            <img class="img-fluid w-100" src="{{ product.img1.url }}" alt="">
                            <div class="text-center py-4">
                                <a class="h6 text-decoration-none text-truncate"
                                   href="{% url 'product:detail' product.id %}">{{ product.title }}</a>
                                <div class="d-flex align-items-center justify-content-center mt-2">
                                    <h5>$ {{ product.price }}</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

                <div class="col-12">
                    <nav>
                        <ul class="pagination justify-content-center">
                            {% if page_obj.has_previous %}
                                <li class="page-item active">
                                    <a class="page-link"
                                       href="?page={{ page_obj.previous_page_number }}"><span>Previous</span></a>
                                </li>
                            {% endif %}
                            {% for i in page_obj.paginator.page_range %}
                                {% if page_obj.number == i %}
                                    <li class="page-item active"><a class="page-link"
                                                                    href="?page={{ i }}">{{ i }}</a></li>
                                {% else %}
                                    <li class="page-item "><a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li class="page-item active"><a class="page-link"
                                                                href="?page={{ page_obj.next_page_number }}">Next</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
        <!-- Shop Product End -->
    </div>
    </div>
    <!-- Shop End -->

{% endblock %}